.TH "Apprentissage" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Apprentissage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Structures\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBImage\fP * \fBimage\fP"
.br
.ti -1c
.RI "char * \fBetiquette\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "char* etiquette"

.SS "\fBImage\fP* image"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
