.TH "Apprentissage.h" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Apprentissage.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'gestionnaire_RN\&.h'\fP
.br
\fC#include 'gestionnaire_IO\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBBackProp\fP (\fBRN\fP *, \fBImage\fP *, char *, float)"
.br
.ti -1c
.RI "void \fBSigmoidePrimeZ\fP (float *in, float **out, int taille)"
.br
.ti -1c
.RI "void \fBMultiplicationMatricielleTransposeeTM\fP (float **, float *, float *, int, int)"
.br
.ti -1c
.RI "void \fBMultiplicationMatricielleTransposeeMT\fP (float *, float *, float **, int, int)"
.br
.ti -1c
.RI "void \fBHadamard\fP (float **, float *, float *, int)"
.br
.ti -1c
.RI "void \fBfct_cout\fP (\fBRN\fP, char *)"
.br
.ti -1c
.RI "void \fBModifPoids\fP (float **, float **, int, int, float)"
.br
.ti -1c
.RI "void \fBModifBiais\fP (float *, float *, int, float)"
.br
.ti -1c
.RI "void \fBDelApp\fP (\fBApp\fP *)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void BackProp (\fBRN\fP *, \fBImage\fP *, char *, float)"

.SS "void DelApp (\fBApp\fP *)"

.SS "void fct_cout (\fBRN\fP, char *)"

.SS "void Hadamard (float **, float *, float *, int)"

.SS "void ModifBiais (float *, float *, int, float)"

.SS "void ModifPoids (float **, float **, int, int, float)"

.SS "void MultiplicationMatricielleTransposeeMT (float *, float *, float **, int, int)"

.SS "void MultiplicationMatricielleTransposeeTM (float **, float *, float *, int, int)"

.SS "void SigmoidePrimeZ (float * in, float ** out, int taille)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
