.TH "BMPHead" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMPHead \- 
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char \fBsignature\fP [2]"
.br
.ti -1c
.RI "\fBint32\fP \fBtaille\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBrsv\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBoffsetim\fP"
.br
.ti -1c
.RI "struct \fBBMPImHead\fP \fBimhead\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "struct \fBBMPImHead\fP imhead"

.SS "\fBint32\fP offsetim"

.SS "\fBint32\fP rsv"

.SS "char signature[2]"

.SS "\fBint32\fP taille"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
