.TH "BMPImHead" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMPImHead \- 
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBint32\fP \fBsize_imhead\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBint16\fP \fBnbplans\fP"
.br
.ti -1c
.RI "\fBint16\fP \fBbpp\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBcompression\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBsizeim\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBhres\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBvres\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBcpalette\fP"
.br
.ti -1c
.RI "\fBint32\fP \fBcIpalette\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "\fBint16\fP bpp"

.SS "\fBint32\fP cIpalette"

.SS "\fBint32\fP compression"

.SS "\fBint32\fP cpalette"

.SS "\fBint32\fP height"

.SS "\fBint32\fP hres"

.SS "\fBint16\fP nbplans"

.SS "\fBint32\fP size_imhead"

.SS "\fBint32\fP sizeim"

.SS "\fBint32\fP vres"

.SS "\fBint32\fP width"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
