.TH "COUCHE" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COUCHE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Structures\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "float * \fBA\fP"
.br
.ti -1c
.RI "float * \fBB\fP"
.br
.ti -1c
.RI "float ** \fBW\fP"
.br
.ti -1c
.RI "float * \fBDELTA\fP"
.br
.ti -1c
.RI "float ** \fBDELTA_M\fP"
.br
.ti -1c
.RI "int \fBtaille\fP"
.br
.ti -1c
.RI "struct \fBCOUCHE\fP * \fBprec\fP"
.br
.ti -1c
.RI "struct \fBCOUCHE\fP * \fBsuiv\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "float* A"

.SS "float* B"

.SS "float* DELTA"

.SS "float** DELTA_M"

.SS "struct \fBCOUCHE\fP* prec"

.SS "struct \fBCOUCHE\fP* suiv"

.SS "int taille"

.SS "float** W"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
