.TH "gestionnaire_RN.h" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gestionnaire_RN.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Structures\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBMultiplicationMatriceVecteur\fP (float **, float *, float *, int, int)"
.br
.ti -1c
.RI "void \fBAdditionVecteurVecteur\fP (float *, float *, float *, int)"
.br
.ti -1c
.RI "void \fBSigmoideV\fP (float *, float *, int)"
.br
.ti -1c
.RI "float \fBSigmoide\fP (float)"
.br
.ti -1c
.RI "\fBRN\fP * \fBinitialisation\fP (\fBINFO_RN\fP *)"
.br
.ti -1c
.RI "void \fBRemplissage\fP (\fBRN\fP rn)"
.br
.ti -1c
.RI "void \fBAjout_couche_Fin\fP (\fBRN\fP *rn, int taille)"
.br
.ti -1c
.RI "void \fBAjoutPremiereCouche\fP (\fBRN\fP *rn, int taille)"
.br
.ti -1c
.RI "void \fBPropagation\fP (\fBImage\fP *, \fBRN\fP)"
.br
.ti -1c
.RI "char ** \fBReconnaissance\fP (\fBRN\fP)"
.br
.ti -1c
.RI "void \fBlibererRN\fP (\fBRN\fP *rn)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void AdditionVecteurVecteur (float *, float *, float *, int)"

.SS "void Ajout_couche_Fin (\fBRN\fP * rn, int taille)"

.SS "void AjoutPremiereCouche (\fBRN\fP * rn, int taille)"

.SS "\fBRN\fP* initialisation (\fBINFO_RN\fP *)"

.SS "void libererRN (\fBRN\fP * rn)"

.SS "void MultiplicationMatriceVecteur (float **, float *, float *, int, int)"

.SS "void Propagation (\fBImage\fP *, \fBRN\fP)"

.SS "char** Reconnaissance (\fBRN\fP)"

.SS "void Remplissage (\fBRN\fP rn)"

.SS "float Sigmoide (float)"

.SS "void SigmoideV (float *, float *, int)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
