.TH "gestionnaire_IO.h" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gestionnaire_IO.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Structures\&.h'\fP
.br
\fC#include 'gestionnaire_RN\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBImage\fP * \fBChargerBmp\fP (const char *fichier, int, int)"
.br
.ti -1c
.RI "\fBImage\fP * \fBChargerMnist\fP (const char *fichier, int, int)"
.br
.ti -1c
.RI "int \fBSauver\fP (\fBImage\fP *, const char *fichier)"
.br
.ti -1c
.RI "\fBImage\fP * \fBNouvelleImage\fP (int w, int h)"
.br
.ti -1c
.RI "\fBImage\fP * \fBCopieImage\fP (\fBImage\fP *)"
.br
.ti -1c
.RI "void \fBSetPixel\fP (\fBImage\fP *, int i, int j, \fBPixel\fP p)"
.br
.ti -1c
.RI "\fBPixel\fP \fBGetPixel\fP (\fBImage\fP *, int i, int j)"
.br
.ti -1c
.RI "void \fBDelImage\fP (\fBImage\fP *)"
.br
.ti -1c
.RI "char * \fBChargerEtiquetteMNIST\fP (const char *path)"
.br
.ti -1c
.RI "\fBApp\fP * \fBChargementCoupleAttIn\fP (char *repertoire_app, int w_max, int h_max)"
.br
.ti -1c
.RI "\fBINFO_RN\fP * \fBChargerInfo\fP ()"
.br
.ti -1c
.RI "\fBRN\fP * \fBChargerRN\fP (\fBINFO_RN\fP *info)"
.br
.ti -1c
.RI "void \fBSaveRN\fP (\fBRN\fP)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "\fBApp\fP* ChargementCoupleAttIn (char * repertoire_app, int w_max, int h_max)"

.SS "\fBImage\fP* ChargerBmp (const char * fichier, int, int)"

.SS "char* ChargerEtiquetteMNIST (const char * path)"

.SS "\fBINFO_RN\fP* ChargerInfo ()"

.SS "\fBImage\fP* ChargerMnist (const char * fichier, int, int)"

.SS "\fBRN\fP* ChargerRN (\fBINFO_RN\fP * info)"

.SS "\fBImage\fP* CopieImage (\fBImage\fP *)"

.SS "void DelImage (\fBImage\fP *)"

.SS "\fBPixel\fP GetPixel (\fBImage\fP *, int i, int j)"

.SS "\fBImage\fP* NouvelleImage (int w, int h)"

.SS "int Sauver (\fBImage\fP *, const char * fichier)"

.SS "void SaveRN (\fBRN\fP)"

.SS "void SetPixel (\fBImage\fP *, int i, int j, \fBPixel\fP p)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
