.TH "gestionnaire_IO.c" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gestionnaire_IO.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <sys/dir\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'gestionnaire_IO\&.h'\fP
.br

.SS "Structures de données"

.in +1c
.ti -1c
.RI "struct \fBBMPImHead\fP"
.br
.ti -1c
.RI "struct \fBBMPHead\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_CRT_SECURE_NO_WARNINGS\fP"
.br
.ti -1c
.RI "#define \fBdebug\fP   printf('line : %d in function : %s in file %s\\n',__LINE__,__func__,__FILE__);"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef int \fBint32\fP"
.br
.ti -1c
.RI "typedef short \fBint16\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBImage\fP * \fBNouvelleImage\fP (int w, int h)"
.br
.ti -1c
.RI "\fBImage\fP * \fBCopieImage\fP (\fBImage\fP *I)"
.br
.ti -1c
.RI "void \fBDelImage\fP (\fBImage\fP *I)"
.br
.ti -1c
.RI "void \fBSetPixel\fP (\fBImage\fP *I, int i, int j, \fBPixel\fP p)"
.br
.ti -1c
.RI "\fBPixel\fP \fBGetPixel\fP (\fBImage\fP *I, int i, int j)"
.br
.ti -1c
.RI "\fBImage\fP * \fBChargerBmp\fP (const char *fichier, int w_max, int h_max)"
.br
.ti -1c
.RI "int \fBSauver\fP (\fBImage\fP *I, const char *fichier)"
.br
.ti -1c
.RI "\fBImage\fP * \fBChargerMnist\fP (const char *path, int w_max, int h_max)"
.br
.ti -1c
.RI "char * \fBChargerEtiquetteMNIST\fP (const char *path)"
.br
.ti -1c
.RI "\fBApp\fP * \fBChargementCoupleAttIn\fP (char *repertoire_app, int w_max, int h_max)"
.br
.ti -1c
.RI "\fBINFO_RN\fP * \fBChargerInfo\fP ()"
.br
.ti -1c
.RI "\fBRN\fP * \fBChargerRN\fP (\fBINFO_RN\fP *info)"
.br
.ti -1c
.RI "void \fBSaveRN\fP (\fBRN\fP rn)"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define _CRT_SECURE_NO_WARNINGS"

.SS "#define debug   printf('line : %d in function : %s in file %s\\n',__LINE__,__func__,__FILE__);"

.SH "Documentation des définitions de type"
.PP 
.SS "typedef short \fBint16\fP"

.SS "typedef int \fBint32\fP"

.SH "Documentation des fonctions"
.PP 
.SS "\fBApp\fP* ChargementCoupleAttIn (char * repertoire_app, int w_max, int h_max)"

.SS "\fBImage\fP* ChargerBmp (const char * fichier, int w_max, int h_max)"

.SS "char* ChargerEtiquetteMNIST (const char * path)"

.SS "\fBINFO_RN\fP* ChargerInfo ()"

.SS "\fBImage\fP* ChargerMnist (const char * path, int w_max, int h_max)"

.SS "\fBRN\fP* ChargerRN (\fBINFO_RN\fP * info)"

.SS "\fBImage\fP* CopieImage (\fBImage\fP * I)"

.SS "void DelImage (\fBImage\fP * I)"

.SS "\fBPixel\fP GetPixel (\fBImage\fP * I, int i, int j)"

.SS "\fBImage\fP* NouvelleImage (int w, int h)"

.SS "int Sauver (\fBImage\fP * I, const char * fichier)"

.SS "void SaveRN (\fBRN\fP rn)"

.SS "void SetPixel (\fBImage\fP * I, int i, int j, \fBPixel\fP p)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
