.TH "Image" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Structures\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "\fBPixel\fP * \fBdat\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "\fBPixel\fP* dat"

.SS "int h"

.SS "int w"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
