.TH "INFO_RN" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INFO_RN \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Structures\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char ** \fBetiquettes\fP"
.br
.ti -1c
.RI "char * \fBnom\fP"
.br
.ti -1c
.RI "char * \fBdate\fP"
.br
.ti -1c
.RI "char * \fBrepertoire\fP"
.br
.ti -1c
.RI "int \fBreussite\fP"
.br
.ti -1c
.RI "int \fBechec\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "char* date"

.SS "int echec"

.SS "char** etiquettes"

.SS "int h"

.SS "char* nom"

.SS "char* repertoire"

.SS "int reussite"

.SS "int w"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
