.TH "interface.c" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interface.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'interface\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBnombreReseau\fP ()"
.br
.RI "\fINombre de Réseaux de neurones existant\&. \fP"
.ti -1c
.RI "void \fBviderContainer\fP (GtkWidget *data)"
.br
.RI "\fIVider le contenu de la fenetre\&. \fP"
.ti -1c
.RI "void \fBretourAccueille\fP (GtkWidget *widget, gpointer data)"
.br
.RI "\fIRetourner a la page d'accueille\&. \fP"
.ti -1c
.RI "void \fBtraitement\fP (GtkWidget *widget, gpointer data)"
.br
.RI "\fILance le traitement d'une image\&. \fP"
.ti -1c
.RI "void \fBresultatTraitement\fP (GtkWidget *widget, gpointer data)"
.br
.RI "\fIAffiche le résultat du traitement d'une image\&. \fP"
.ti -1c
.RI "void \fBselectReseau\fP (GtkWidget *widget, gpointer data)"
.br
.RI "\fISelection d'un reseau de neurone\&. \fP"
.ti -1c
.RI "void \fBlancerApprentissage\fP (GtkWidget *widget, gpointer data)"
.br
.RI "\fILancer l'apprentissage du réseau de neurones\&. \fP"
.ti -1c
.RI "void * \fBfctThreadApp\fP (void *arg)"
.br
.RI "\fIFonction appeler par le thread qui fait l'apprentissage du reseau de neurone\&. \fP"
.ti -1c
.RI "void \fBpage_principale\fP (\fBINFO_FENETRE\fP *fenetre)"
.br
.RI "\fIPage d'accueille du programme\&. \fP"
.ti -1c
.RI "void \fBcreation\fP (GtkWidget *widget, gpointer data)"
.br
.RI "\fIInterface de creation d'un reseau de neurones\&. \fP"
.ti -1c
.RI "void \fBcreationRN\fP (GtkWidget *widget, gpointer data)"
.br
.ti -1c
.RI "void \fBcreer_folder_selection\fP (GtkButton *button, gpointer data)"
.br
.RI "\fISelection du dossier ou ce trouverons les données pour l'apprentissage\&. \fP"
.ti -1c
.RI "void \fBcreer_file_selection\fP (GtkWidget *widget, gpointer data)"
.br
.ti -1c
.RI "void \fBquitter\fP (GtkWidget *widget, gpointer data)"
.br
.RI "\fILorsque l'on quitte la fenetre\&. \fP"
.ti -1c
.RI "void \fBafficherInterface\fP ()"
.br
.RI "\fIContenant toute l'interface et les fonction\&. \fP"
.ti -1c
.RI "void \fBmatrice\fP (GtkWidget *widget, gpointer data)"
.br
.RI "\fIAffichage de la matrice des poid du reseau de neurones\&. \fP"
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void afficherInterface ()"

.PP
Contenant toute l'interface et les fonction\&. 
.SS "void creation (GtkWidget * widget, gpointer data)"

.PP
Interface de creation d'un reseau de neurones\&. Recuperation des données et sauvegarde du réseau de neurones\&.
.PP
\fBParamètres:\fP
.RS 4
\fIwidget\fP Le widget qui est associer a la fonction\&. 
.br
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "void creationRN (GtkWidget * widget, gpointer data)"

.SS "void creer_file_selection (GtkWidget * widget, gpointer data)"

.SS "void creer_folder_selection (GtkButton * button, gpointer data)"

.PP
Selection du dossier ou ce trouverons les données pour l'apprentissage\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIwidget\fP Le widget qui est associer a la fonction\&. 
.br
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "void * fctThreadApp (void * arg)"

.PP
Fonction appeler par le thread qui fait l'apprentissage du reseau de neurone\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIarg\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "void lancerApprentissage (GtkWidget * widget, gpointer data)"

.PP
Lancer l'apprentissage du réseau de neurones\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIwidget\fP Le widget qui est associer a la fonction\&. 
.br
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "void matrice (GtkWidget * widget, gpointer data)"

.PP
Affichage de la matrice des poid du reseau de neurones\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIwidget\fP Le widget qui est associer a la fonction\&. 
.br
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "int nombreReseau ()"

.PP
Nombre de Réseaux de neurones existant\&. 
.PP
\fBRenvoie:\fP
.RS 4
int nombre de Réseau\&. 
.RE
.PP

.SS "void page_principale (\fBINFO_FENETRE\fP * fenetre)"

.PP
Page d'accueille du programme\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIfenetre\fP La fenetre qu'on affichera dans l'accueille\&. 
.RE
.PP

.SS "void quitter (GtkWidget * widget, gpointer data)"

.PP
Lorsque l'on quitte la fenetre\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIwidget\fP Le widget qui est associer a la fonction\&. 
.br
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "void resultatTraitement (GtkWidget * widget, gpointer data)"

.PP
Affiche le résultat du traitement d'une image\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIwidget\fP Le widget qui est associer a la fonction\&. 
.br
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "void retourAccueille (GtkWidget * widget, gpointer data)"

.PP
Retourner a la page d'accueille\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIwidget\fP Le widget qui est associer a la fonction\&. 
.br
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "void selectReseau (GtkWidget * widget, gpointer data)"

.PP
Selection d'un reseau de neurone\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIwidget\fP Le widget qui est associer a la fonction\&. 
.br
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "void traitement (GtkWidget * widget, gpointer data)"

.PP
Lance le traitement d'une image\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIwidget\fP Le widget qui est associer a la fonction\&. 
.br
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SS "void viderContainer (GtkWidget * data)"

.PP
Vider le contenu de la fenetre\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIdata\fP Pour le passage de la structure \fBINFO_FENETRE\fP\&. 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
