.TH "RN" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RN \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Structures\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBINFO_RN\fP * \fBinfo\fP"
.br
.ti -1c
.RI "\fBListe_Couche\fP \fBcouche_deb\fP"
.br
.ti -1c
.RI "\fBListe_Couche\fP \fBcouche_fin\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "\fBListe_Couche\fP couche_deb"

.SS "\fBListe_Couche\fP couche_fin"

.SS "\fBINFO_RN\fP* info"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
