.TH "Structures.h" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Structures.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "struct \fBPixel\fP"
.br
.ti -1c
.RI "struct \fBImage\fP"
.br
.ti -1c
.RI "struct \fBCOUCHE\fP"
.br
.ti -1c
.RI "struct \fBINFO_RN\fP"
.br
.ti -1c
.RI "struct \fBRN\fP"
.br
.ti -1c
.RI "struct \fBApprentissage\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBdebug\fP   printf('line : %d in function : %s in file %s\\n',__LINE__,__func__,__FILE__);"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBPixel\fP \fBPixel\fP"
.br
.ti -1c
.RI "typedef struct \fBImage\fP \fBImage\fP"
.br
.ti -1c
.RI "typedef struct \fBCOUCHE\fP \fBCOUCHE\fP"
.br
.ti -1c
.RI "typedef \fBCOUCHE\fP * \fBListe_Couche\fP"
.br
.ti -1c
.RI "typedef struct \fBINFO_RN\fP \fBINFO_RN\fP"
.br
.ti -1c
.RI "typedef struct \fBRN\fP \fBRN\fP"
.br
.ti -1c
.RI "typedef struct \fBApprentissage\fP \fBApp\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define debug   printf('line : %d in function : %s in file %s\\n',__LINE__,__func__,__FILE__);"

.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fBApprentissage\fP \fBApp\fP"

.SS "typedef struct \fBCOUCHE\fP \fBCOUCHE\fP"

.SS "typedef struct \fBImage\fP  \fBImage\fP"

.SS "typedef struct \fBINFO_RN\fP \fBINFO_RN\fP"

.SS "typedef \fBCOUCHE\fP* \fBListe_Couche\fP"

.SS "typedef struct \fBPixel\fP  \fBPixel\fP"

.SS "typedef struct \fBRN\fP \fBRN\fP"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
