.TH "test.c" 3 "Vendredi 25 Mai 2018" "ProjetRn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'test\&.h'\fP
.br
\fC#include <gtk/gtk\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWHT\fP   '\\x1B[8;47m'"
.br
.ti -1c
.RI "#define \fBBLK\fP   '\\x1B[8;40m'"
.br
.ti -1c
.RI "#define \fBRESET\fP   '\\x1B[0m'"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBtest_reconnaissance\fP (char *path)"
.br
.ti -1c
.RI "void \fBtest_chargerMNIST\fP (char *path)"
.br
.ti -1c
.RI "void \fBtest_ChargerEtiquetteMNIST\fP (char *path)"
.br
.ti -1c
.RI "void \fBtest_ChargementCoupleAttIn\fP (char *path)"
.br
.ti -1c
.RI "void \fBtest_Apprentissage\fP (char *path)"
.br
.ti -1c
.RI "void \fBtest_MultiplicationMatricielleTransposeeTM\fP ()"
.br
.ti -1c
.RI "void \fBtest_MultiplicationMatricielleTransposeeMT\fP ()"
.br
.ti -1c
.RI "void \fBtest_Propagation\fP ()"
.br
.ti -1c
.RI "void \fBtest_BackProp\fP ()"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define BLK   '\\x1B[8;40m'"

.SS "#define RESET   '\\x1B[0m'"

.SS "#define WHT   '\\x1B[8;47m'"

.SH "Documentation des fonctions"
.PP 
.SS "int main (int argc, char ** argv)"

.SS "void test_Apprentissage (char * path)"

.SS "void test_BackProp ()"

.SS "void test_ChargementCoupleAttIn (char * path)"

.SS "void test_ChargerEtiquetteMNIST (char * path)"

.SS "void test_chargerMNIST (char * path)"

.SS "void test_MultiplicationMatricielleTransposeeMT ()"

.SS "void test_MultiplicationMatricielleTransposeeTM ()"

.SS "void test_Propagation ()"

.SS "void test_reconnaissance (char * path)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour ProjetRn à partir du code source\&.
